baseURL = "/"
languageCode = "ja"
title = "やましろ街事典"

disableKinds = ["taxonomy", "term"]

[permalinks.page]
term-categories = "/categories/:filename/"

[permalinks.section]
term-categories = "/categories/"
