baseURL = "/"
languageCode = "ja"
title = "Yamashiro Machijiten"

disableKinds = ["taxonomy", "term"]

[permalinks.page]
term-categories = "/categories/:slug/"

[permalinks.section]
term-categories = "/categories/"
