backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "site/static/uploads"
public_folder: "/uploads"

collections:
  - name: "home"
    label: "ホーム"
    files:
      - file: "site/content/_index.md"
        label: "ホーム"
        name: "home"
        fields:
          - { label: "タイトル", name: "title", widget: "string" }
          - { label: "説明", name: "description", widget: "text" }
          - { label: "本文", name: "body", widget: "markdown" }

  - name: "categories"
    label: "カテゴリ"
    folder: "site/content/term-categories"
    path: "{{slug}}/_index"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "カテゴリ名", name: "title", widget: "string" }
      - { label: "説明", name: "description", widget: "text", required: false }
      - { label: "本文", name: "body", widget: "markdown", required: false }

  - name: "terms"
    label: "用語"
    folder: "site/content/terms"
    path: "{{slug}}/index"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "用語", name: "title", widget: "string" }
      - { label: "よみがな", name: "kana", widget: "string" }
      - label: "カテゴリ"
        name: "categories"
        widget: "relation"
        collection: "categories"
        search_fields: ["title"]
        display_fields: ["title"]
        value_field: "{{slug}}"
        multiple: true
        required: false
      - { label: "意味の解説文", name: "body", widget: "markdown" }
