backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "site/static/uploads"
public_folder: "/uploads"

collections:
  - name: "home"
    label: "ホーム"
    files:
      - file: "site/content/_index.md"
        label: "ホーム"
        name: "home"
        fields:
          - { label: "タイトル", name: "title", widget: "string" }
          - { label: "説明", name: "description", widget: "text" }
          - { label: "本文", name: "body", widget: "markdown" }

  - name: "posts"
    label: "記事"
    folder: "site/content/posts"
    path: "{{slug}}/index"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "date", widget: "datetime" }
      - { label: "説明", name: "description", widget: "text", required: false }
      - { label: "下書き", name: "draft", widget: "boolean", default: false }
      - { label: "本文", name: "body", widget: "markdown" }
